# Generated by Django 5.0.1 on 2024-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_a', models.TextField()),
                ('side_b', models.TextField()),
            ],
        ),
    ]
